name: Release

on:
    push:
        tags:
            - '*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2.3.4
            -   name: Prepare
                id: prep
                shell: bash
                run: |
                    VERSION=${GITHUB_REF#refs/tags/}
                    echo ::set-output name=version::${VERSION}
            -   name: Install node.js
                uses: actions/setup-node@v2.1.5
                with:
                    node-version: '15'
            -   name: Install .NET Core 3.1
                uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '3.1.x'
            -   name: Install .NET 5.0
                uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '5.0.x'
            -   name: Build js
                working-directory: src/${{ env.PROJECT}}/Web
                run: |
                    - npm ci
                    - npm run prod
            -   name: Create package
                run: dotnet pack /p:Version=${{ steps.prep.outputs.version }} -c Release src/${{ env.PROJECT}}
            -   name: Publish nuget package
                run: dotnet nuget push packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
                    
